### ISSUE TITLE
SundialJobScheduler.stopJob does not actually interrupt threads

### ISSUE THREAD

**Issue by reftel** [knowm/Sundial#25]
The documentation for `SundialJobScheduler.stopJob` states:

> Triggers a Job interrupt on all Jobs matching the given Job Name

However, is a job is running and is blocked in e.g. a call to `Object.wait`, then the job just sits there. It does not appear that `Thread.interrupt` is called on the thread hosting the job.

If this is intentional, then the documentation should be updated to reflect this, though I would very much prefer to have a way of interrupting jobs.

**Comment by timmolter** [comment]
Thanks. I had the mechanism explained in the README, and I added it to the `stopJob` methods. I agree that an interrupt mechanism would be nice to have as well. I'll leave this issue open as a feature request.

**Comment by timmolter** [comment]
I just looked into this and there's really now way to do it. Each Job runs in its own thread and I can call interrupt on the thread but I cannot then use that event to interrupt a wait or sleep or infinite loop in the Job itself. That's what the `checkTerminated();` mechanism is for, which is essentially the same thing you'd have to do in the case if Jobs were Runnables directly, which would need some kind of poison flag as demonstrated here: <https://stackoverflow.com/a/13476257/1625820>

 For an example see `SampleJob9.java`. In a loop within the Job you should just add a call to `checkTerminated();`.
