### ISSUE TITLE
JobListener Support in Sundial

### ISSUE THREAD

**Issue by ponvino** [knowm/Sundial#41]
Sundial version of quartz is not having support to add globalJobListeners.

Is there any workaround or way to add global listeners.

We are trying implement some sort of job chaining using this job listener capability.

Please advise on the same. Thanks,

**Comment by timmolter** [comment]
I honestly don't remember what a `globalJobListeners` is and what it did or when/if i removed it from the original Quartz code. You'll have to dig into the code yourself and see what you can find.
