### ISSUE TITLE
Run a single job explicitly / stay alive until finished

### ISSUE THREAD

**Issue by black-snow** [knowm/Sundial#42]
Hello,

I've successfully used Sundial to run my cron jobs.
Now I'm trying to add a CLI switch to my application to run a single job and then exit. I struggle with this.

How can I get the scheduler up and running and just submit a single job without it executing my jobs.xml? I tried to

```java
SundialJobScheduler.createScheduler(1);
SundialJobScheduler.addJob("whatever", MyJob.class);
SundialJobScheduler.startJob("whatever");
```

but that doesn't seem to do anything. So I came up with this:

```java
SundialJobScheduler.startScheduler(1, "my.jobs.package");
SundialJobScheduler.addJob("whatever", MyJob.class);
SundialJobScheduler.startJob("whatever");
```

which hopefully just runs the job I told it to run. But I then have issues to keep the application alive until the job is finished.

I deadlock the app for my cron jobs with:

```java
        try {
            Object lock = new Object();
            synchronized (lock) {
                while (true) {
                    lock.wait();
                }
            }
        }
        catch (InterruptedException ex) {
            LOGGER.info("Caught ^c, shutting down.");
        }
```

but that's not a solution for the new use case. I thus tried to wait for the job to finish via

```java
            try {
                while (SundialJobScheduler.isJobRunning("whatever")) {
                    LOGGER.debug("job still running");
                    Thread.sleep(2000);
                }
                LOGGER.debug("job finished");
            }
            catch (InterruptedException | SundialSchedulerException e) {
                LOGGER.error("Error in job?", e);
            }
```

but this, too, exits before the job is actually finished.

Is there a simple solution that I missed?

**Comment by timmolter** [comment]
I pushed a fix, but I'd like for you to test it. Can you run the latest SNAPSHOT jar and test it? Also see `SingleRun.java`.

**Comment by black-snow** [comment]
@timmolter thanks for the reply!
Is there a prebuilt jar for that snapshot?

**Comment by black-snow** [comment]
Found it: https://oss.sonatype.org/content/repositories/snapshots/org/knowm/sundial/

**Comment by black-snow** [comment]
2.2.0-SNAPSHOT seems to work fine.

> 11:43:27.958 INFO  org.knowm.sundial.plugins.AnnotationJobTriggerPlugin - Found 2 jobs in package.
11:43:27.958 INFO  org.quartz.QuartzScheduler - Scheduler started.
11:43:27.958 INFO  x.y.jobs.Upload - upload job running
11:43:27.958 DEBUG x.y.jobs.Upload - File found.
11:43:28.004 DEBUG x.y.jobs.Upload - Authorized with GDrive.
11:43:28.067 INFO  org.quartz.QuartzScheduler - Scheduler shutting down...
11:43:28.067 INFO  org.quartz.QuartzScheduler - Scheduler paused.
11:43:28.067 INFO  org.quartz.QuartzScheduler - Threadpool shutting down...
11:43:28.067 INFO  org.quartz.core.SimpleThreadPool - Waiting for Job to shutdown: xyz : xyz-trigger
11:43:28.989 DEBUG x.y.jobs.Upload - File already exists. Updating ...
11:43:31.263 INFO  x.y.jobs.Upload - upload job finished
11:43:31.263 INFO  org.quartz.QuartzScheduler - Scheduler shutdown complete.
11:43:31.279 INFO  org.quartz.plugins.management.ShutdownHookPlugin - Shutting down Quartz...

I followed the single run example and removed the semi-busy wait loop:

```java
SundialJobScheduler.startScheduler(1, "x.y.jobs");
SundialJobScheduler.addJob(MANUAL_UPLOAD_JOB, Upload.class);
SundialJobScheduler.startJob(MANUAL_UPLOAD_JOB);
SundialJobScheduler.shutdown();
return 0;
```

**Comment by black-snow** [comment]
@timmolter Thanks for the quick fix :)
I'll close this for now.

**Comment by timmolter** [comment]
Glad it helped! I'll push a release soon, maybe today.
