### ISSUE TITLE
Scheduler cannot load all annotated job classes from multiple locations

### ISSUE THREAD

**Issue by ligasgr** [knowm/Sundial#55]
Hi,
This issue is related or a duplicate of https://github.com/knowm/Sundial/issues/36
When the package to scan for annotated classes exists in multiple locations (e.g. two source roots: main and test going to separate output directories but both ending up on the classpath or a main and additional jar) then only one of those locations will be picked up and scanned.

The solution would seem to be to either modify existing method 
https://github.com/knowm/Sundial/blob/develop/src/main/java/org/quartz/classloading/ClassLoadHelper.java -> `URL getResource(String name);` or add a new one that would allow multiple resource locations `URL[] getResource(String name);` and use it for finding package locations to iterate over in: https://github.com/knowm/Sundial/blob/develop/src/main/java/org/knowm/sundial/plugins/AnnotationJobTriggerPlugin.java -> `public Set<Class<? extends Job>> getJobClasses(String pkgname)`

Please let me know if you would have some time to look into that in near future and if not then I can try to submit a PR.

**Comment by timmolter** [comment]
PLease submit a PR. Thanks!

**Comment by ligasgr** [comment]
In order to add a test for this new functionality I would either have to add a dependency on external jar dependency with test job or introduce a new maven module in this project but in order to avoid circular dependencies I would have to add another one for annotations.
Another option is to leave this new code path only test using existing regression tests based on running one code path (where there is only one matching location of the package).
@timmolter What is your preference here?

**Comment by ligasgr** [comment]
Please see initial check-in without the additional test cases in https://github.com/knowm/Sundial/pull/58.
If this is sufficient please merge if happy otherwise please let me know.

**Comment by timmolter** [comment]
thanks!
